suppressPackageStartupMessages(library(ChIPseeker))
#library(TxDb.Mmusculus.UCSC.mm10.knownGene)
suppressPackageStartupMessages(library(clusterProfiler))
suppressPackageStartupMessages(library(org.Mm.eg.db))
suppressPackageStartupMessages(library(rtracklayer))
suppressPackageStartupMessages(library(GenomicRanges))
suppressPackageStartupMessages(library(AnnotationDbi))
suppressPackageStartupMessages(library(GenomicFeatures))
suppressPackageStartupMessages(library(stringr))

argv <- commandArgs(TRUE)
peak=readPeakFile(argv[1],as="GRanges")
txdb=loadDb(argv[2])
#promoter <- getPromoters(TxDb=txdb, upstream=3000, downstream=3000)
peakAnno <- annotatePeak(argv[1], tssRegion=c(-3000, 3000),TxDb=txdb, annoDb="org.Mm.eg.db")
pA=as.data.frame(peakAnno)
anno.db=basename(argv[2])
anno.db=str_replace(anno.db,".TxDb.sqlite","")
anno.db=str_replace_all(anno.db,".gtf","")
anno.db=str_replace_all(anno.db,"gencode.vM25.annotation","")
write.table(pA,file=paste(argv[1],anno.db,"annotation.xls",sep="."),sep="\t",quote=F,col.names=T,row.names=F)
